# g++ -g -std=c++11 -fsanitize=address  -o run-test main.cc
all:
	clang++ -g -std=c++11 -fsanitize=address -fno-omit-frame-pointer -o run-test main.cc


test:
	clang++ -g -std=c++11 -o run-test main.cc
